version: "{build}"

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      CMAKE_GENERATOR: Visual Studio 16 2019
      QT_BASEDIR: C:/Qt/5.9/msvc2017_64

configuration:
  - Debug
  - Release

install:
  - ps: new-item -itemtype directory -path C:\glm | out-null
  - ps: (new-object net.webclient).DownloadFile("https://github.com/g-truc/glm/releases/download/0.9.9.7/glm-0.9.9.7.zip", 'C:/glm.zip')
  - ps: expand-archive 'C:/glm.zip' -destinationpath 'C:\'

before_build:
  - cmd: cd C:/projects
  - cmd: md build
  - cmd: cd build
  - cmd: cmake -G "%CMAKE_GENERATOR%" -DADD_CXX_FLAGS="/IC:/glm" -DCMAKE_PREFIX_PATH=%QT_BASEDIR%/lib/cmake/Qt5 -DCMAKE_INSTALL_PREFIX=. ../atmosphere-textures-generator

build_script:
    - cmd: cmake --build . --config %configuration%

for:
-
  matrix:
    only:
      - configuration: Release
  after_build:
    - cmd: cmake --build . --config %configuration% --target install
    - cmd: 7z a atg.zip atmosphere-textures-generator
    - cmd: appveyor PushArtifact atg.zip
-
  matrix:
    only:
      - configuration: Debug
  after_build:
    - cmd: cmake --build . --config %configuration% --target install
    - cmd: for %%F in (msvcp140d vcruntime140d) do copy "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\redist\debug_nonredist\x64\Microsoft.VC140.DebugCRT\%%F.dll" atmosphere-textures-generator
    - cmd: copy "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Redist\MSVC\14.25.28508\debug_nonredist\x64\Microsoft.VC142.DebugCRT\vcruntime140_1d.dll" atmosphere-textures-generator
    - cmd: copy "C:\Program Files (x86)\Windows Kits\10\bin\x64\ucrt\ucrtbased.dll" atmosphere-textures-generator
    - cmd: 7z a atg.zip atmosphere-textures-generator
    - cmd: appveyor PushArtifact atg.zip
