version: "{build}"

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      CMAKE_GENERATOR: Visual Studio 16 2019
      QT_BASEDIR: C:/Qt/5.9/msvc2017_64

configuration:
  - Release
#  - Debug

install:
# Get and extract GLM
  - ps: new-item -itemtype directory -path C:\glm | out-null
  - ps: (new-object net.webclient).DownloadFile("https://github.com/g-truc/glm/releases/download/0.9.9.7/glm-0.9.9.7.zip", 'C:/glm.zip')
  - ps: expand-archive 'C:/glm.zip' -destinationpath 'C:\'
# Get and extract Eigen
  - ps: new-item -itemtype directory -path C:\eigen | out-null
  - ps: (new-object net.webclient).DownloadFile("https://gitlab.com/libeigen/eigen/-/archive/3.3.7/eigen-3.3.7.zip", 'C:/eigen-src.zip')
  - ps: expand-archive 'C:/eigen-src.zip' -destinationpath 'C:\'
# Install Eigen into its final prefix
  - cmd: cd C:\eigen-3.3.7 && mkdir build && cd build && cmake -G "%CMAKE_GENERATOR%" -DBUILD_TESTING=OFF -DCMAKE_INSTALL_PREFIX=C:/eigen ..
  - cmd: cmake --build . --target install

before_build:
  - cmd: cd C:/projects && mkdir build && mkdir install && cd build
  - cmd: cmake -G "%CMAKE_GENERATOR%" -DADD_CXX_FLAGS="/IC:/glm" -DCMAKE_PREFIX_PATH="%QT_BASEDIR%/lib/cmake/Qt5;C:/eigen/share/eigen3/cmake" -DCMAKE_INSTALL_PREFIX=../install ../CalcMySky

build_script:
    - cmd: cmake --build . --config %configuration% -- /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    - cmd: set PATH=%PATH%;%QT_BASEDIR%\bin
    - cmd: ctest -C %configuration%

for:
-
  matrix:
    only:
      - configuration: Release
  after_build:
    - cmd: cmake --build . --config %configuration% --target install
    - cmd: 7z a CalcMySky.zip ../install/CalcMySky
    - cmd: 7z l CalcMySky.zip
    - cmd: appveyor PushArtifact CalcMySky.zip
-
  matrix:
    only:
      - configuration: Debug
  after_build:
    - cmd: cmake --build . --config %configuration% --target install
    - cmd: for %%F in (msvcp140d vcruntime140d) do copy "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\redist\debug_nonredist\x64\Microsoft.VC140.DebugCRT\%%F.dll" CalcMySky
    - cmd: copy "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Redist\MSVC\14.25.28508\debug_nonredist\x64\Microsoft.VC142.DebugCRT\vcruntime140_1d.dll" CalcMySky
    - cmd: copy "C:\Program Files (x86)\Windows Kits\10\bin\x64\ucrt\ucrtbased.dll" CalcMySky
    - cmd: 7z a CalcMySky.zip CalcMySky
    - cmd: appveyor PushArtifact CalcMySky.zip
